# Generated by Django 4.1 on 2022-10-09 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Sabab nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Guruh nomi')),
                ('time', models.CharField(max_length=50, verbose_name='Vaqti')),
                ('kunlari', models.CharField(max_length=350, verbose_name='Hafta kunlari')),
                ('payment', models.PositiveIntegerField(default=0, verbose_name="To'lov")),
                ('days_in_month', models.PositiveIntegerField(default=0, verbose_name='Kun soni')),
                ('active', models.BooleanField(default=False, verbose_name='aktiv/aktiv emas')),
                ('own', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismingizni kiriting', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Fan nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=150, verbose_name='Familiyasi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher_img/', verbose_name="O'qituvchi rasmi")),
                ('tel_num', models.CharField(blank=True, max_length=50, verbose_name='Telefon raqami')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Bitta dars uchun narx')),
                ('countsub', models.PositiveIntegerField(default=0, verbose_name='Bir oydagi darslar soni')),
                ('allprice', models.PositiveIntegerField(default=0, verbose_name='Jami maosh')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='main.subjects')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=150, verbose_name="to'langan vaqt")),
                ('price', models.PositiveIntegerField(default=0, verbose_name="to'langan summa")),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=150, verbose_name='Familiyasi')),
                ('brith', models.CharField(max_length=50, verbose_name="Tug'ulgan sanasi")),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_img/', verbose_name="O'quvchi rasmi")),
                ('password_img', models.ImageField(blank=True, upload_to='students_passport', verbose_name='Pasort rasmi')),
                ('tel_num', models.CharField(blank=True, max_length=50, verbose_name='Telefon raqami')),
                ('place', models.CharField(max_length=50, verbose_name='Yashash manzili')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Chegirma')),
                ('countsub', models.PositiveIntegerField(default=0, verbose_name='Bir oydagi darslar soni')),
                ('allprice', models.PositiveIntegerField(default=0, verbose_name="Jami to'lov")),
                ('called', models.BooleanField(default=False, verbose_name='called/not called')),
                ('camewith', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='main.camewith')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='main.group')),
                ('own', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=100, verbose_name="To'lagan sanasi")),
                ('payed', models.PositiveIntegerField(default=0, verbose_name='summasi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='main.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers_group', to='main.subjects'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='main.teacher'),
        ),
        migrations.CreateModel(
            name='CameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=100, verbose_name='Kelgan sanasi')),
                ('came', models.BooleanField(default=False, verbose_name='keldi/kelmadi')),
                ('apset', models.BooleanField(default=False, verbose_name='sababli/sababsiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
